### PR TITLE
replace vocab IRIs with list of terms IRIs

### PR DESCRIPTION
**Pull request by baskaufs**
@tucotuco @timrobertson100 @peterdesmet @mdoering @pzermoglio @qgroom The IRIs currently in the term comments for degreeOfEstablishment, pathway, and establishmentMeans are the controlled vocabulary IRIs, which unfortunately don't actually lead people directly to the controlled values, term definitions, etc.

In this pull request, I have changed the IRIs to the term list IRIs, which actually provide complete information on the terms and are more appropriate.

### CODE REVIEW

**Review by tucotuco — APPROVED** [review]

**Comment by peterdesmet** [comment]
Great! The previous implementation was indeed not super helpful.

**Comment by peterdesmet** [comment]
@baskaufs what website will be fixed if we merge this? The main problem to me is the http://rs.tdwg.org/dwcdoe/ URL at https://dwc.tdwg.org/terms/#dwc:establishmentMeans for me.

**Comment by baskaufs** [comment]
Fix QRG, fix List of Terms doc, fix automatically generated machine-readable representations of dwc:pathway, dwc:establishmentMeans, dwc:degreeOfEstablishment

**Comment by peterdesmet** [comment]
Ok, then let's merge and let me know if I can help running some scripts.

**Pull request merged**
